<?php
// $Id$

/**
 * Implementation of hook_install().
 * 
 * In drupal 5, you cannot alter menu, so you have to make sure 
 * publishcontent_menu (hook_menu) is called before node_menu
 * so that node/{$nid} is registered by publishcntent_menu rather
 * than node_menu.
 */
function publishcontent_install() {
   db_query("UPDATE {system} SET weight='-1' WHERE name = 'publishcontent' AND type='module';");
}
